[package]
name = "notify-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
notify-rust = "4.10.0"
actix-web = "4.4.0"
serde = { version = "1.0", features = ["derive"] }
